### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by kholiqsantosa** [Desamod/NotPixelBot#3]
![Screenshot_2024-09-30-09-24-36-971_com server auditor ssh client-edit~2](https://github.com/user-attachments/assets/946d4e9f-024e-4931-a8d9-88517b629beb)

`2024-09-30 09:24:17 | ERROR    | 105 - utama | Unknown error during Authorizatio
n: list index out of range`

How do I fix this? Do you have any ideas?

I've already tried deleting the session and creating a new one, changing proxies and even running without a proxy, but the result is still the same.

**Comment by Desamod** [comment]
Fixed, check latest update
